name: CI BOT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Configurazione Python 3.12.2
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.2"

    - name: Installazione dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install pytest python-telegram-bot
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Esecuzione Test con Pytest
      run: |
        PYTHONPATH=. pytest
